local monit = peripheral.wrap("top")
monit.clear()
while true do
monit.setCursorPos(1,1)
monit.write("/------")
monit.setCursorPos(1,2)
monit.write("-------")
monit.setCursorPos(1,3)
monit.write("-------")
monit.setCursorPos(1,4)
monit.write("-------")
monit.setCursorPos(1,5)
monit.write("-------")

monit.setCursorPos(1,1)
monit.write("-/-----")
monit.setCursorPos(1,2)
monit.write("/------")
monit.setCursorPos(1,3)
monit.write("-------")
monit.setCursorPos(1,4)
monit.write("-------")
monit.setCursorPos(1,5)
monit.write("-------")

monit.setCursorPos(1,1)
monit.write("--/----")
monit.setCursorPos(1,2)
monit.write("-/-----")
monit.setCursorPos(1,3)
monit.write("/------")
monit.setCursorPos(1,4)
monit.write("-------")
monit.setCursorPos(1,5)
monit.write("-------")

monit.setCursorPos(1,1)
monit.write("---/---")
monit.setCursorPos(1,2)
monit.write("--/-----")
monit.setCursorPos(1,3)
monit.write("-/-----")
monit.setCursorPos(1,4)
monit.write("/------")
monit.setCursorPos(1,5)
monit.write("-------")


monit.setCursorPos(1,1)
monit.write("----/--")
monit.setCursorPos(1,2)
monit.write("---/---")
monit.setCursorPos(1,3)
monit.write("--/----")
monit.setCursorPos(1,4)
monit.write("-/-----")
monit.setCursorPos(1,5)
monit.write("/------")

monit.setCursorPos(1,1)
monit.write("-----/-")
monit.setCursorPos(1,2)
monit.write("----/--")
monit.setCursorPos(1,3)
monit.write("---/---")
monit.setCursorPos(1,4)
monit.write("--/----")
monit.setCursorPos(1,5)
monit.write("-/-----")

monit.setCursorPos(1,1)
monit.write("------/")
monit.setCursorPos(1,2)
monit.write("-----/-")
monit.setCursorPos(1,3)
monit.write("----/--")
monit.setCursorPos(1,4)
monit.write("---/---")
monit.setCursorPos(1,5)
monit.write("--/----")

monit.setCursorPos(1,1)
monit.write("-------")
monit.setCursorPos(1,2)
monit.write("-----/-")
monit.setCursorPos(1,3)
monit.write("----/--")
monit.setCursorPos(1,4)
monit.write("---/---")
monit.setCursorPos(1,5)
monit.write("--/----")

monit.setCursorPos(1,1)
monit.write("-------")
monit.setCursorPos(1,2)
monit.write("-------/")
monit.setCursorPos(1,3)
monit.write("-----/-")
monit.setCursorPos(1,4)
monit.write("----/--")
monit.setCursorPos(1,5)
monit.write("---/---")

monit.setCursorPos(1,1)
monit.write("-------")
monit.setCursorPos(1,2)
monit.write("-------")
monit.setCursorPos(1,3)
monit.write("------/")
monit.setCursorPos(1,4)
monit.write("-----/-")
monit.setCursorPos(1,5)
monit.write("----/--")

monit.setCursorPos(1,1)
monit.write("-------")
monit.setCursorPos(1,2)
monit.write("-------")
monit.setCursorPos(1,3)
monit.write("-------")
monit.setCursorPos(1,4)
monit.write("------/")
monit.setCursorPos(1,5)
monit.write("-----/-")

monit.setCursorPos(1,1)
monit.write("-------")
monit.setCursorPos(1,2)
monit.write("-------")
monit.setCursorPos(1,3)
monit.write("-------")
monit.setCursorPos(1,4)
monit.write("-------")
monit.setCursorPos(1,5)
monit.write("------/")

end
