local monit = peripheral.wrap("top")
monit.clear()
monit.setCursorPos(1,1)
monit.write("-------//------")
monit.setCursorPos(1,2)
monit.write("------//------")
monit.setCursorPos(1,3)
monit.write("-----//-------")
