local monit = peripheral.wrap("top")
monit.clear()
monit.setCursorPos(1,1)
monit.write("/------")
monit.setCursorPos(1,2)
monit.write("-------")
monit.setCursorPos(1,3)
monit.write("-------")
monit.setCursorPos(1,4)
monit.write("-------")
monit.setCursorPos(1,5)
monit.write("-------")
monit.setCursorPos(1,6)
monit.write("-------")
monit.setCursorPos(1,7)
monit.write("-------")
